version: '3.8'

services:
  todo-app:
    build: .
    ports:
      - "8000:8000"
    restart: always
    command: python -m src.app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./src:/app/src
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
