name: Commit Checks

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Create virtual environment and install dependencies
        run: |
          python3 -m venv venv  # Sanal ortamı oluştur
          ls -l venv/bin  # Sanal ortam dosyalarının doğru oluşturulup oluşturulmadığını kontrol et
          . venv/bin/activate  # Sanal ortamı aktive et
          pip install --upgrade pip  # pip'i güncelle
          pip install -r requirements.txt  # Bağımlılıkları yükle

      - name: Verify Python version
        run: |
          echo "Python path: $(which python3)"
          echo "Python version: $(python3 --version)"

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint with black
        run: |
          . venv/bin/activate
          black --check .

  tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests with pytest
        run: |
          . venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q
