name: Commit Checks

on: [push]

env:
  PIP_ROOT_USER_ACTION: ignore
  PYTHON_VERSION: 3.12

jobs:
  style-check:
    name: Style Check
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate || echo "venv aktif edilemedi!"
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run style check
        run: |
          source venv/bin/activate
          python3 make style-check

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          source venv/bin/activate
          python3 make test
