name: Commit Checks

on: [push]

env:
  PIP_ROOT_USER_ACTION: ignore
  PYTHON_VERSION: 3.13

jobs:
  style-check:
    name: Style Check
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Check Python version
        run: python --version

      - name: Install virtualenv
        run: |
          pip install virtualenv

      - name: Create virtualenv
        run: |
          python3 -m venv venv
          ls -l venv/bin  # Sanal ortamın doğru oluşturulup oluşturulmadığını kontrol et

      - name: Activate virtualenv
        run: |
          source venv/bin/activate
          echo "Virtual environment activated"

      - name: Install dependencies
        run: |
          pip install black
          pip install isort
          pip install -r requirements.txt

      - name: Run style check
        run: |
          make format

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Check Python version
        run: python --version

      - name: Install virtualenv
        run: |
          pip install virtualenv

      - name: Create virtualenv
        run: |
          python3 -m venv venv
          ls -l venv/bin  # Sanal ortamın doğru oluşturulup oluşturulmadığını kontrol et

      - name: Activate virtualenv
        run: |
          source venv/bin/activate
          echo "Virtual environment activated"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          make test
