name: Commit Checks

on: [push]

env:
  PIP_ROOT_USER_ACTION: ignore
  PYTHON_VERSION: 3.12

jobs:
  style-check:
    name: Style Check
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install virtualenv
        run: |
          pip install virtualenv

      - name: Create and activate virtualenv
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run style check
        run: |
          make format

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install virtualenv
        run: |
          pip install virtualenv

      - name: Create and activate virtualenv
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          make test
